--- 
abstract: Utility for instrumenting code using Log::Log4perl.
author: 
  - Matt Luker  C<< <mluker@rshtech.com> >>
build_requires: 
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
distribution_type: module
generated_by: Module::Install version 0.680
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RSH-Logging
no_index: 
  directory: 
    - inc
    - t
requires: 
  IO::File: 0
  Log::Log4perl: 0
  Scalar::Util: 0
  Text::SimpleTable: 0
  Time::HiRes: 0
  perl: 5.8.0
version: 0.3.2
